# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: YData123

# Short description (goes below the title; it will also be used in the RSS feed)
description: An Introduction to Data Science

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://ydata123.org/

# favicon
favicon: favicon.ico
